apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stateful-app-netpol
  labels:
    app: stateful-app
    app.kubernetes.io/name: stateful-guestbook
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app: stateful-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from ingress controllers
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  # Allow traffic from monitoring systems
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
  # Allow traffic from same namespace for demo purposes
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS for secure communications
  - to: []
    ports:
    - protocol: TCP
      port: 443
