apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-app-pv
  labels:
    app: stateful-app
    component: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/tmp/stateful-demo-data" # Use /tmp which is more accessible
    type: DirectoryOrCreate
