apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-app-pvc
  labels:
    app: stateful-app
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
