apiVersion: v1
kind: ServiceAccount
metadata:
  name: stateful-app-sa
  namespace: default
  labels:
    app: stateful-app
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: stateful-app-role
  labels:
    app: stateful-app
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stateful-app-rolebinding
  namespace: default
  labels:
    app: stateful-app
subjects:
- kind: ServiceAccount
  name: stateful-app-sa
  namespace: default
roleRef:
  kind: Role
  name: stateful-app-role
  apiGroup: rbac.authorization.k8s.io
