apiVersion: v1
kind: Namespace
metadata:
  name: stateful-production
  labels:
    # Pod Security Standards for production - maximum security
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn-version: latest
    # Environment labels
    app.kubernetes.io/name: stateful-guestbook
    app.kubernetes.io/component: namespace
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: kubectl
    environment: production
  annotations:
    security.kubernetes.io/policy: "Production environment with restricted Pod Security Standard"
    security.kubernetes.io/rationale: "Production workloads require maximum security controls"
    compliance.kubernetes.io/standards: "CIS-1.6,NIST-800-190"
