---
# Production storage configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-app-pvc
spec:
  resources:
    requests:
      storage: 5Gi  # Larger storage for production
