---
# Base Kustomization for Stateful Scaling Demo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: stateful-scaling-demo
  annotations:
    config.kubernetes.io/local-config: "true"

# Base resources
resources:
  - security-config.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - rbac.yaml
  - network-policy-simple.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Common labels applied to all resources
commonLabels:
  app: stateful-app
  app.kubernetes.io/name: stateful-guestbook
  app.kubernetes.io/component: demo
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  demo.kubernetes.io/purpose: "stateful-scaling-demonstration"
  demo.kubernetes.io/educational: "true"

# Image transformations
images:
  - name: stateful-guestbook
    newTag: latest
